### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by texastoland**
Fixes broken tests related to `testdouble`. Also runs `standard --fix`. Parent commit of other PRs.

### CODE REVIEW

**Comment by searls** [comment]
I appreciate this, but I think if we upgrade deps we should also add a lockfile (e.g. don't ignore yarn.lock), however at this point (for the sake of consistency with most of our other node packages), I'd prefer to lock this down npm and package-lock.json. If you can get a green build with upgraded deps and a package-lock.json, I'd be glad to merge

**Comment by rosston** [comment]
Looks like tests are "broken" because the upgraded `testdouble` package depends on a package using the `...` operator, which is unsupported in node < 6. I think getting a green build is probably going to require updating appveyor.yml and .travis.yml. @searls, maybe we switch to node 6, 8, and 10?

**Comment by searls** [comment]
Thanks @rosston :+1:

**Comment by rosston** [comment]
@texastoland I tried bumping the node versions on CI in a [separate branch](https://github.com/testdouble/scripty/compare/bump-ci-node-versions), but I see now that failures on newer node versions are why you were updating `testdouble` along with all the other dependencies. You want to handle updating the node versions in this PR since it seems like that needs to happen in lockstep with the `testdouble` upgrade?

**Comment by texastoland** [comment]
@searls I can shrinkwrap no problem. It still makes sense to ignore `yarn.lock` since Yarn can read `package-json.lock` too.

@rosston 👍🏽 I'll push shortly. Do we still need to support 6.x? 7.0.0 was released 2 years ago. If I make more PRs beyond the ones today I'd like to clean up the code (e.g. async-await instead of callbacks). Babel wouldn't bother me though.

**Comment by texastoland** [comment]
> I'd like to clean up the code

@searls assuming you don't mind e.g. same logic with today's best practices (async-await, pure functions, possibly types). Something else I'd really like are Jest snapshot tests. I wonder if you'd mind replacing teenytest.

**Comment by texastoland** [comment]
👍🏽 thank you @rosston I didn't know about EOL dates.

**Comment by searls** [comment]
Before merge, please revert the changes to delete the trailing `\n` chars from the handful of scripts in this PR. I still would also prefer not listing `yarn.lock` in the `gitignore`. With those assuming we're green I'm happy to merge

**Comment by rosston** [comment]
@searls I believe the change only deletes _double_ trailing `\n` chars, presumably from running `standard --fix` ("Multiple blank lines not allowed." is a `standard` rule [as of v9](https://standardjs.com/changelog.html#900---2017-02-28)).

**Comment by texastoland** [comment]
Confirmed whitespace changes were automated by `standard --fix` as part of the existing tests. Why not list `yarn.lock`? It's popular enough that it's recommended in every React tutorial, generated automatically, but not interoperable with npm. The alternative is any potential contributor must add it to their global ignore.

**Comment by searls** [comment]
Thanks @rosston on pointing out that about standard.

@texastoland, I'd only be open to adopting language features in current Node LTS versions, which means no `async/await` in Node 6, IIRC

**Comment by texastoland** [comment]
> which means no async/await in Node 6, IIRC

Assuming you don't use `@babel/node` or `ts-node` (although I understand if prefer not TypeScript) or just compile to `dist`?

The rest sounds good? If so I request a refactor branch to make smaller PRs. Otherwise the diff will be horrific.

Did you understand my point about `yarn.lock`? I know about `.git/info/exclude` but only after a few years and I've never had to use it. Basically if you don't want ti to be committed it seems apt to ignore.

**Comment by searls** [comment]
Correct, this library is not compiled. Any refactors would need to only use libraries that work under Node 6

**Comment by searls** [comment]
Again, I'd prefer not adding yarn.lock to .gitignore. If I added every possible developer-local file to .gitignore that someone might accidentally add some day (.idea, .code, etc), I'd have to maintain some very long standard .gitignore to copy-paste between all 300 of the repos I own.

**Comment by texastoland** [comment]
> Correct, this library is not compiled

Compilation is part of the refactor question. Today the code is challenging to contribute to in part because it was written without Promises, arrow functions, etc. The point of Babel, et al. is that 2 years from now it won't look like it were written 2 years ago (since Node has been slow to adopt standards). Also no form of static checking would be possible without it.

> (.idea, .code, etc), I'd have to maintain some very long standard .gitignore to copy-paste

[That exists](https://github.com/github/gitignore/blob/master/Node.gitignore) right? I see your point about not ignoring `.vscode`. I'll remove that since it can be easily globally ignored (unlike `yarn.lock`). But Yarn was responsible for more than 6 million downloads last month despite a stronger caching strategy than npm.

🤷🏽‍♂️ I'll do it but that's my opinion as someone actively contributing to JS since before jQuery. I sent a DM in case you want to chat.

**Comment by jasonkarns** [comment]
Add `yarn.lock` to your `.git/info/exclude` if you want to ignore yarn.lock locally.

**Comment by texastoland** [comment]
👍🏽 roger. Feel free to close the others. I'm going to work on a fork. Thanks for an inspiring project. I think it's more applicable today than when you wrote it.

**Pull request closed without merging**
